In [1]:
import numpy as np

# Create a 1D array of numbers from 0 to 9

In [2]:
arr1 = np.arange(10)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract all odd numbers from arr

In [4]:
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2[ arr2 % 2 == 1]

array([1, 3, 5, 7, 9])

# Replace all odd numbers in arr with -1


In [6]:
arr2[arr2 % 2 == 1] = -1

In [7]:
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Replace all odd numbers in arr with -1 without changing original array

In [9]:
arr3 = np.arange(10)

In [13]:
newArr = np.where(arr3 % 2 == 1, -1, arr3)

In [14]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
newArr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#  Convert a 1D array to a 2D array with 2 rows

In [16]:
arr5 = np.array([0,0,1,1,2,3,4,5,6,7])

In [17]:
arr5.reshape(2,-1)

array([[0, 0, 1, 1, 2],
       [3, 4, 5, 6, 7]])

# Stack arrays a and b vertically

In [18]:
a = np.arange(10).reshape(2,-1)

In [19]:
b = np.repeat(1, 10).reshape(2,-1)

In [20]:
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Stack arrays a and b Horizontally

In [18]:
a = np.arange(10).reshape(2,-1)

In [19]:
b = np.repeat(1, 10).reshape(2,-1)

In [22]:
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [23]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# generate custom sequences in numpy without hardcoding?


In [25]:
a = np.array([1,2,3])

In [26]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# get the common items between two python numpy arrays?

In [29]:
a = np.array([1,2,3,2,3])

In [30]:

b = np.array([7,2,10,2,7])

In [31]:
np.intersect1d(a,b)

array([2])

# remove from one array those items that exist in another?

In [35]:
x = np.array([0,1,2])

In [37]:
y = np.array([2,0,1])

In [39]:
np.setdiff1d(x,y)

array([], dtype=int32)

# get the positions where elements of two arrays match?

In [40]:
a = np.array([0,1,3,5])

In [41]:
b =np.array([2,1,4,5])

In [42]:
np.where(a == b)

(array([1, 3], dtype=int64),)

It returns the index numbers where both array elements match

# extract all numbers between a given range from a numpy array?

In [47]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [50]:
i = np.where((a >= 5) & (a <= 10))

In [51]:
i

(array([1, 3, 4], dtype=int64),)

In [52]:
a[i]

array([ 6,  9, 10])

# swap two columns in a 2d numpy array?


In [61]:
r = np.arange(9).reshape(3,3)

In [62]:
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
r[:,(1,0,2)]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# reverse the rows of a 2D array?

In [64]:
r = np.arange(9).reshape(3,3)

In [65]:
r[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# reverse the columns of a 2D array?

In [66]:
r = np.arange(9).reshape(3,3)

In [67]:
r[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# create a 2D array containing random floats between 5 and 10?

In [68]:
r = np.arange(9).reshape(3,3)

In [69]:
rand_arr = np.random.uniform(5,10, size=(5,3))

In [70]:
rand_arr

array([[6.12044099, 8.13102786, 7.57415766],
       [8.29880529, 6.63716952, 8.77067653],
       [6.59777464, 8.18795117, 6.81358345],
       [9.93238933, 8.64813256, 6.25272703],
       [8.09830103, 9.48758563, 8.37330826]])

# print only 3 decimal places in python numpy array?

In [71]:
rand_arr = np.random.random((5,3))

In [73]:
np.set_printoptions(precision=3)

In [74]:
rand_arr

array([[0.554, 0.143, 0.508],
       [0.861, 0.815, 0.417],
       [0.55 , 0.932, 0.356],
       [0.676, 0.219, 0.642],
       [0.016, 0.026, 0.984]])

# 18-limit the number of items printed in output of numpy array?

In [76]:
arr = np.arange(99)

In [77]:
np.set_printoptions(threshold=6)

In [80]:
arr

array([ 0,  1,  2, ..., 96, 97, 98])

# 19-print the full numpy array without truncating

In [93]:
arr = np.arange(9)

In [ ]:
np.set_printoptions(threshold=np.nan)

# 20-extract a particular column from 1D array of tuples?

In [104]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [106]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [107]:
iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

# 21-extract a particular column from 1D array of tuples?

In [116]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [122]:
iris = np.genfromtxt(url, delimiter=',', dtype=None)

C:\Users\Fine Traders\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [123]:
species = np.array([row[4] for row in iris])


In [124]:
species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S18')

# 22-convert a 1d array of tuples to a 2d numpy array?

In [125]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])

In [126]:
iris_2d[:4]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

# 23-compute the mean, median, standard deviation of a numpy array?

In [127]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [128]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [129]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


# 24-find the percentile scores of a numpy array?

In [130]:
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

# 25-insert values at random positions in an array?

In [131]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [132]:
i, j = np.where(iris_2d)

In [133]:
np.random.seed(100)

In [134]:
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

In [135]:
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 ...
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


# 26-find the position of missing values in numpy array?

In [136]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [137]:
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 5
Position of missing values: 
 (array([13, 17, 47, 53, 91], dtype=int64),)


# 27-filter a numpy array based on two or more conditions?

In [138]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [139]:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

# 28-drop rows that contain a missing value from a numpy array?

In [140]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [141]:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [142]:
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

# 29-find the correlation between two columns of a numpy array?

In [145]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [146]:
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048718

# 30-find if a given array has any null values?

In [147]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [148]:
np.isnan(iris_2d).any()

False

# 31-replace all missing values with 0 in a numpy array?

In [149]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [150]:
iris_2d[np.isnan(iris_2d)] = 0

In [151]:
iris_2d[:4]

array([[5.1, 0. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

# 32-find the count of unique values in a numpy array?

In [152]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [153]:
species = np.array([row.tolist()[4] for row in iris])

In [154]:
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50], dtype=int64))

# 33-convert a numeric to a categorical (text) array?

In [155]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [156]:
# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

In [157]:
# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

In [158]:
petal_length_cat[:4]


['small', 'small', 'small', 'small']

# 34-create a new column from existing columns of a numpy array?

In [159]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [160]:
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

In [161]:
# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

In [162]:
# Add the new column
out = np.hstack([iris_2d, volume])

In [163]:
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

# 35-get the second largest value of an array when grouped by another array?

In [164]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [165]:
# Get the species and petal length columns
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

In [166]:
np.unique(np.sort(petal_len_setosa))[-2]

1.7

# 36-sort a 2D array by a column

In [167]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [168]:
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 ...
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


# 37-find the most frequent value in a numpy array?

In [169]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [170]:
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


# 38-find the position of the first occurrence of a value greater than a given value?

In [171]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [172]:
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50], dtype=int64)

# 39-replace all values greater than a given value to a given cutoff?

In [173]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [174]:
np.clip(a, a_min=10, a_max=30)

array([27.63, 14.64, 21.8 , ..., 10.  , 30.  , 14.43])

# 40-get the positions of top n values from a numpy array?

In [175]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [176]:
print(a.argsort())

[ 4 13  5 ...  3 10 15]
